In [7]:
from sklearn.datasets import fetch_20newsgroups
train_all=fetch_20newsgroups(subset='train')
print (train_all.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [2]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
import sklearn
sklearn.__version__

'0.21.2'

In [10]:
simple_dataset=fetch_20newsgroups(subset='train',
                                  categories=['comp.sys.mac.hardware', 'soc.religion.christian', 'rec.sport.hockey'])

In [14]:
print(simple_dataset.data[0])

From: erik@cheshire.oxy.edu (Erik Adams)
Subject: HELP!!  My Macintosh "luggable" has lines on its screen!
Organization: Occidental College, Los Angeles, CA 90041 USA.
Distribution: comp
Lines: 20

Okay, I don't use it very much, but I would like for it to keep working
correctly, at least as long as Apple continues to make System software
that will run on it, if slowly :-)

Here is the problem:  When the screen is tilted too far back, vertical
lines appear on the screen.  They are every 10 pixels or so, and seem
to be affected somewhat by opening windows and pulling down menus.
It looks to a semi-technical person like there is a loose connection
between the screen and the rest of the computer.

I am open to suggestions that do not involve buying a new computer,
or taking this one to the shop.  I would also like to not have
to buy one of Larry Pina's books.  I like Larry, but I'm not sure
I feel strongly enough about the computer to buy a service manual
for it.

On a related note:  what

In [32]:
print(simple_dataset.DESCR)

.. _20newsgroups_dataset:

The 20 newsgroups text dataset
------------------------------

The 20 newsgroups dataset comprises around 18000 newsgroups posts on
20 topics split in two subsets: one for training (or development)
and the other one for testing (or for performance evaluation). The split
between the train and test set is based upon a messages posted before
and after a specific date.

This module contains two loaders. The first one,
:func:`sklearn.datasets.fetch_20newsgroups`,
returns a list of the raw texts that can be fed to text feature
extractors such as :class:`sklearn.feature_extraction.text.CountVectorizer`
with custom parameters so as to extract feature vectors.
The second one, :func:`sklearn.datasets.fetch_20newsgroups_vectorized`,
returns ready-to-use features, i.e., it is not necessary to use a feature
extractor.

**Data Set Characteristics:**

    =================   ==========
    Classes                     20
    Samples total            18846
    Dimensionality 

In [33]:
print(simple_dataset.feature_names)

AttributeError: feature_names

In [29]:
import numpy as np

In [35]:
print(simple_dataset.data[-1])

From: dlecoint@garnet.acns.fsu.edu (Darius_Lecointe)
Subject: Re: Sabbath Admissions 5of5
Organization: Florida State University
Lines: 21

I find it interesting that cls never answered any of the questions posed. 
Then he goes on the make statements which make me shudder.  He has
established a two-tiered God.  One set of rules for the Jews (his people)
and another set for the saved Gentiles (his people).  Why would God
discriminate?  Does the Jew who accepts Jesus now have to live under the
Gentile rules.

God has one set of rules for all his people.  Paul was never against the
law.  In fact he says repeatedly that faith establishes rather that annuls
the law.  Paul's point is germane to both Jews and Greeks.  The Law can
never be used as an instrument of salvation.  And please do not combine
the ceremonial and moral laws in one.

In Matt 5:14-19 Christ plainly says what He came to do and you say He was
only saying that for the Jews's benefit.  Your Christ must be a
politician, speaki

In [36]:
print(simple_dataset.data[-2])

From: scialdone@nssdca.gsfc.nasa.gov (John Scialdone)
Subject: CUT Vukota and Pilon!!!
News-Software: VAX/VMS VNEWS 1.41    
Organization: NASA - Goddard Space Flight Center
Lines: 32

I have been to all 3 Isles/Caps tilts at the Crap Centre this year, all Isles
wins and there is no justification for Vukota and Pilon to play for the Isles.
Vukota is absolutely the worst puck handler in the world!! He couldn't hit a
bull in the ass with a banjo!! Al must remember a few years back when Mick 
scored 3 goals in one period against the Caps in a 5-3 Isles win. I was there
and was astonished as was the rest of the crowd. Wake-up Al!!! Years later he's
gotten worse. He's a cheap shot artist and always ends up getting
stupid/senseless penalties. I think he would make a good police officier!!!

As for Pilon, he can't carry the puck out to center ice by himself. He either
makes a bad pass resulting in a turnover, or he attempts to bring the puck 
towards the neutral zone and skates right into an 

In [37]:
print(len(simple_dataset.data))

1777


In [39]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer=CountVectorizer(max_df=500, min_df=10)
matrix=vectorizer.fit_transform(simple_dataset.data)

In [40]:
print(matrix.shape)

(1777, 3767)


In [41]:
from sklearn.cluster.hierarchical import AgglomerativeClustering

In [42]:
model=AgglomerativeClustering(n_clusters=3, affinity='cosine', linkage='complete')
preds=model.fit_predict(matrix.toarray())
print(list(preds))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [52]:
print(matrix.toarray()[1:10,1:10])

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [45]:
type(matrix)

scipy.sparse.csr.csr_matrix

In [53]:
print(matrix[0])

  (0, 877)	1
  (0, 880)	1
  (0, 2243)	1
  (0, 1136)	1
  (0, 2358)	1
  (0, 2820)	1
  (0, 2108)	1
  (0, 3035)	1
  (0, 1229)	1
  (0, 3262)	1
  (0, 1366)	1
  (0, 3305)	1
  (0, 551)	1
  (0, 1961)	2
  (0, 619)	2
  (0, 294)	1
  (0, 3322)	1
  (0, 2325)	1
  (0, 620)	1
  (0, 1831)	1
  (0, 3285)	1
  (0, 2422)	1
  (0, 301)	1
  (0, 855)	3
  (0, 2868)	1
  :	:
  (0, 900)	1
  (0, 354)	1
  (0, 2048)	1
  (0, 1991)	1
  (0, 926)	1
  (0, 3722)	1
  (0, 1905)	1
  (0, 2273)	1
  (0, 3600)	1
  (0, 3555)	1
  (0, 2413)	1
  (0, 69)	1
  (0, 838)	1
  (0, 1121)	1
  (0, 3553)	1
  (0, 625)	1
  (0, 319)	1
  (0, 2056)	1
  (0, 810)	1
  (0, 2991)	4
  (0, 1846)	1
  (0, 2082)	1
  (0, 1659)	1
  (0, 239)	1
  (0, 1246)	3


In [56]:
len(vectorizer.get_feature_names())

3767

In [57]:
print(vectorizer.get_feature_names()[877])

connect


## KMeans

In [66]:
from sklearn.cluster import KMeans
model=KMeans(n_clusters=3, random_state=1)
preds=model.fit_predict(matrix.toarray())
print(preds)

[0 0 0 ... 0 0 0]


In [60]:
print (simple_dataset.target)

[0 0 1 ... 0 1 2]


In [63]:
np.sum(simple_dataset.target)

1798

Процент ошибок

In [67]:
mapping={2:1, 1:2, 0:0}
mapped_preds=[mapping[pred] for pred in preds]
print (float(sum(mapped_preds !=simple_dataset.target))/len(simple_dataset.target))

0.6741699493528419


In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
clf=LogisticRegression()
print (cross_val_score(clf, matrix, simple_dataset.target).mean())

0.9780395267593631


## SVD+KMeans

In [71]:
from sklearn.decomposition import TruncatedSVD

In [73]:
model = KMeans(n_clusters=3, random_state=42)
svd=TruncatedSVD(n_components=1000, random_state=123)
features=svd.fit_transform(matrix)
preds=model.fit_predict(features)
print(preds)
print(simple_dataset.target)

[0 0 0 ... 0 0 0]
[0 0 1 ... 0 1 2]
